modLoader="javafml"
loaderVersion="[36,)"
license="Public domain"

[[mods]]
modId="headbump"
version="1.0"
displayName="Head Bump"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/head-bump"
#logoFile="logo.png"
#credits=""
authors="StephenBarnes"
description='''
Inflict damage when player hits their head against a ceiling.'''

[[dependencies.headbump]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.headbump]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
